// Mock products data for development when database is not available
export const mockProducts = [
  {
    id: 'prod-1',
    name: 'Classic Cotton T-Shirt',
    description: 'Premium 100% cotton t-shirt perfect for custom designs. Soft, comfortable, and durable.',
    category: 'TSHIRT',
    basePrice: 18.99,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      {
        id: 'img-1',
        productId: 'prod-1',
        url: '/images/products/tshirt-white-front.jpg',
        altText: 'White T-Shirt Front',
        isPrimary: true,
        angle: 'front',
      },
      {
        id: 'img-2', 
        productId: 'prod-1',
        url: '/images/products/tshirt-white-back.jpg',
        altText: 'White T-Shirt Back',
        isPrimary: false,
        angle: 'back',
      },
    ],
    variants: [
      {
        id: 'var-1',
        productId: 'prod-1',
        name: 'White - Small',
        sku: 'TSH-WHT-SM',
        price: 18.99,
        colorName: 'White',
        colorHex: '#FFFFFF',
        colorSlug: 'white',
        sizeName: 'Small',
        sizeSlug: 'sm',
        stock: 50,
        printfulId: 'printful-1',
        printifyId: null,
      },
      {
        id: 'var-2',
        productId: 'prod-1',
        name: 'White - Medium',
        sku: 'TSH-WHT-MD',
        price: 18.99,
        colorName: 'White',
        colorHex: '#FFFFFF',
        colorSlug: 'white',
        sizeName: 'Medium',
        sizeSlug: 'md',
        stock: 75,
        printfulId: 'printful-2',
        printifyId: null,
      },
      {
        id: 'var-3',
        productId: 'prod-1',
        name: 'Black - Medium',
        sku: 'TSH-BLK-MD',
        price: 19.99,
        colorName: 'Black',
        colorHex: '#000000',
        colorSlug: 'black',
        sizeName: 'Medium',
        sizeSlug: 'md',
        stock: 60,
        printfulId: 'printful-3',
        printifyId: null,
      },
    ],
    specs: {
      id: 'spec-1',
      productId: 'prod-1',
      material: '100% Ringspun Cotton',
      care: JSON.stringify(['Machine wash cold', 'Tumble dry low', 'Do not bleach']),
      sizing: 'Regular fit, true to size',
      printAreaFront: JSON.stringify({ width: 10, height: 12, x: 0, y: 4 }),
      printAreaBack: JSON.stringify({ width: 10, height: 12, x: 0, y: 4 }),
    },
  },
  {
    id: 'prod-2',
    name: 'Classic Baseball Cap',
    description: 'Adjustable cotton baseball cap with structured front panel, perfect for embroidered or vinyl designs.',
    category: 'CAP',
    basePrice: 22.99,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      {
        id: 'img-3',
        productId: 'prod-2',
        url: '/images/products/cap-black-front.jpg',
        altText: 'Black Baseball Cap Front',
        isPrimary: true,
        angle: 'front',
      },
      {
        id: 'img-4',
        productId: 'prod-2', 
        url: '/images/products/cap-black-side.jpg',
        altText: 'Black Baseball Cap Side',
        isPrimary: false,
        angle: 'side',
      },
    ],
    variants: [
      {
        id: 'var-4',
        productId: 'prod-2',
        name: 'Black - One Size',
        sku: 'CAP-BLK-OS',
        price: 22.99,
        colorName: 'Black',
        colorHex: '#000000',
        colorSlug: 'black',
        sizeName: 'One Size',
        sizeSlug: 'os',
        stock: 40,
        printfulId: 'printful-4',
        printifyId: null,
      },
      {
        id: 'var-5',
        productId: 'prod-2',
        name: 'Navy - One Size',
        sku: 'CAP-NAV-OS',
        price: 22.99,
        colorName: 'Navy',
        colorHex: '#001F3F',
        colorSlug: 'navy',
        sizeName: 'One Size',
        sizeSlug: 'os',
        stock: 35,
        printfulId: 'printful-5',
        printifyId: null,
      },
    ],
    specs: {
      id: 'spec-2',
      productId: 'prod-2',
      material: '100% Cotton Twill',
      care: JSON.stringify(['Spot clean only', 'Air dry', 'Do not iron decoration']),
      sizing: 'Adjustable snapback closure, fits most adults',
      printAreaFront: JSON.stringify({ width: 4, height: 2, x: 0, y: 0 }),
      printAreaBack: null,
    },
  },
  {
    id: 'prod-3',
    name: 'Canvas Tote Bag',
    description: 'Eco-friendly canvas tote bag with reinforced handles. Perfect for screen printed designs.',
    category: 'TOTE_BAG',
    basePrice: 15.99,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [
      {
        id: 'img-5',
        productId: 'prod-3',
        url: '/images/products/tote-natural-front.jpg',
        altText: 'Natural Canvas Tote Front',
        isPrimary: true,
        angle: 'front',
      },
      {
        id: 'img-6',
        productId: 'prod-3',
        url: '/images/products/tote-natural-side.jpg', 
        altText: 'Natural Canvas Tote Side',
        isPrimary: false,
        angle: 'side',
      },
    ],
    variants: [
      {
        id: 'var-6',
        productId: 'prod-3',
        name: 'Natural - One Size',
        sku: 'TOTE-NAT-OS',
        price: 15.99,
        colorName: 'Natural',
        colorHex: '#F5F5DC',
        colorSlug: 'natural',
        sizeName: 'One Size',
        sizeSlug: 'os',
        stock: 80,
        printfulId: 'printful-6',
        printifyId: null,
      },
      {
        id: 'var-7',
        productId: 'prod-3',
        name: 'Black - One Size',
        sku: 'TOTE-BLK-OS',
        price: 16.99,
        colorName: 'Black',
        colorHex: '#000000',
        colorSlug: 'black',
        sizeName: 'One Size', 
        sizeSlug: 'os',
        stock: 65,
        printfulId: 'printful-7',
        printifyId: null,
      },
    ],
    specs: {
      id: 'spec-3',
      productId: 'prod-3',
      material: '10oz 100% Cotton Canvas',
      care: JSON.stringify(['Machine wash cold', 'Air dry', 'Iron if needed']),
      sizing: '15" W x 16" H x 3" D, 22" handle drop',
      printAreaFront: JSON.stringify({ width: 8, height: 10, x: 3.5, y: 3 }),
      printAreaBack: null,
    },
  },
]

// Helper function to filter mock products by category
export function getMockProducts(category?: string) {
  if (!category) {
    return mockProducts
  }
  
  return mockProducts.filter(product => 
    product.category === category.toUpperCase()
  )
}

// Helper function to get a single product by ID
export function getMockProduct(id: string) {
  return mockProducts.find(product => product.id === id)
}